In [39]:
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.model_selection import train_test_split
import random

无风险回报

In [93]:
rf=0.0001115

In [40]:
import yfinance as yf

In [74]:
ticker_list=['0016.HK','2269.HK','1876.HK','0268.HK','1810.HK','2202.HK','0823.HK','0868.HK','0981.HK','1928.HK']

In [111]:
def month_data(x,y):
    stock_data = {}
    for ticker in ticker_list: 
        stock=yf.download(ticker,start=f"2022-{x}-01",end=f'2022-{x}-{y}')
        stock_data[ticker] = stock
    price_data= pd.DataFrame()
    for i in ticker_list: 
         price=stock_data[i]['Adj Close']
         price_data[i]=price 
    stock_log_ret = np.log(price_data/price_data.shift(1))
    stock_price=stock_log_ret[1:]
    return stock_price

In [112]:
jan=month_data('01','31')
jan

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,0016.HK,2269.HK,1876.HK,0268.HK,1810.HK,2202.HK,0823.HK,0868.HK,0981.HK,1928.HK
Date,,,,,,,,,,
2022-01-04,0.001585,-0.051173,-0.014670,0.000000,-0.002153,0.042934,0.010145,-0.006224,-0.012821,0.018672
2022-01-05,-0.001057,-0.043794,-0.007417,-0.014753,-0.035091,0.025533,-0.010874,-0.038181,-0.022839,-0.080405
2022-01-06,-0.009559,-0.012052,0.009877,-0.054539,0.011099,0.002099,-0.008785,-0.011963,0.006579,0.019849
2022-01-07,0.004260,0.030172,0.050310,0.030908,0.007697,0.069342,-0.001472,0.021646,-0.006579,-0.002315
2022-01-10,0.009519,0.023862,-0.018868,0.015103,0.014138,0.026540,0.000000,0.016985,0.006579,0.000000
2022-01-11,0.001052,0.058132,-0.016807,-0.041536,-0.019630,0.007117,-0.008133,0.019803,-0.002188,-0.008144
2022-01-12,-0.003687,0.056556,0.002418,0.028605,0.035699,-0.009501,-0.003719,0.000000,0.023811,0.027652
2022-01-13,-0.003701,-0.016305,-0.024451,0.010788,-0.007467,-0.038934,-0.002985,-0.030385,-0.002141,-0.028820
2022-01-14,0.000000,0.011441,-0.004963,0.000000,-0.002144,-0.017522,0.003730,0.030385,-0.004296,0.068915
2022-01-17,0.000000,-0.023015,-0.013020,0.039963,-0.007539,-0.006079,-0.001490,0.001032,0.005368,0.136529
2022-01-18,0.001588,-0.011148,-0.003029,0.022427,0.006466,0.043258,-0.001493,-0.004132,0.038850,-0.028988
2022-01-19,0.001585,-0.026699,-0.012208,-0.055973,-0.016243,0.026412,0.000747,0.051940,-0.012435,0.004890
2022-01-20,0.003689,0.050516,0.045519,0.008493,0.031169,0.009434,0.017018,0.043276,0.014493,0.026476
2022-01-21,0.025449,-0.019343,0.031290,-0.006363,0.001058,0.004684,0.010219,0.027844,0.003079,0.032713
2022-01-24,-0.004626,-0.022004,0.023420,-0.008547,-0.038798,-0.002339,-0.001453,-0.006889,-0.002051,-0.013889
2022-01-25,-0.017148,-0.024251,-0.002318,-0.017316,-0.032387,-0.038191,-0.010969,-0.028039,-0.023897,-0.030772
2022-01-26,0.000000,-0.070831,0.016111,-0.004376,-0.010268,-0.009780,0.000735,0.000000,0.001051,0.019048
2022-01-27,0.000000,-0.031870,-0.013793,-0.096627,-0.056619,-0.002460,-0.006635,-0.009524,-0.007380,0.004706
2022-01-28,-0.004728,-0.038288,-0.006969,-0.098407,-0.013439,-0.012392,-0.012654,-0.019324,-0.006369,0.013986

In [87]:
jan.sum()

0016.HK    0.004222
2269.HK   -0.160093
1876.HK    0.040434
0268.HK   -0.242151
1810.HK   -0.134453
2202.HK    0.120155
0823.HK   -0.028067
0868.HK    0.058249
0981.HK   -0.003190
1928.HK    0.180102
dtype: float64

In [169]:
np.dot(jan.var(),

0016.HK    0.000069
2269.HK    0.001370
1876.HK    0.000473
0268.HK    0.001595
1810.HK    0.000543
2202.HK    0.000758
0823.HK    0.000060
0868.HK    0.000618
0981.HK    0.000222
1928.HK    0.001940
dtype: float64

In [114]:
market_data=yf.download('^HSI',start='2022-01-01',end="2023-01-01",interval="1mo")
market_price=market_data['Adj Close']
market_log_ret = np.log(market_price/market_price.shift(1))
market_log_price=market_log_ret[1:]
market_log_price

[*********************100%***********************]  1 of 1 completed

Date
2022-02-01   -0.046842
2022-03-01   -0.032039
2022-04-01   -0.042129
2022-05-01    0.015331
2022-06-01    0.020548
2022-07-01   -0.081122
2022-08-01   -0.010078
2022-09-01   -0.147213
2022-10-01   -0.159272
2022-11-01    0.236049
2022-12-01    0.061730
Name: Adj Close, dtype: float64

function for weight

In [90]:
def random_weight(n, m):
    numbers = [random.random() for _ in range(n)]
    summation = sum(numbers)
    k = m / summation
    return [i * k for i in numbers]

In [103]:
def get_best_weight(month):
    port_weights=[]
    port_sharpe=[]
    for i in range(1000):
        weights=np.array(random_weight(10,1))
        return_portfolio=np.dot(month.sum(),weights)-rf
        volatility =np.sqrt(np.dot(weights.T, np.dot(month.cov()*len(month), weights))) 
        sharpe= return_portfolio/volatility
        port_sharpe.append(sharpe)
        port_weights.append(weights)
    best_port_stock=port_weights[port_sharpe.index(sharpe.max())]
    return best_port_stock

In [104]:
get_best_weight(jan)

array([0.12759554, 0.1016507 , 0.1672311 , 0.06181428, 0.15178134,
       0.12400215, 0.08145463, 0.08159704, 0.01478901, 0.0880842 ])

In [116]:
feb=month_data('02','28')
feb

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,0016.HK,2269.HK,1876.HK,0268.HK,1810.HK,2202.HK,0823.HK,0868.HK,0981.HK,1928.HK
Date,,,,,,,,,,
2022-02-07,0.002582,0.013113,0.004619,0.017242,-0.012136,0.007326,0.002234,-0.009390,0.003163,0.008909
2022-02-08,0.000516,-0.258340,-0.013921,-0.004283,-0.025975,-0.009780,0.007413,-0.002361,-0.008457,0.028417
2022-02-09,0.012295,-0.010497,0.023096,0.054293,0.046520,-0.025381,0.008824,0.016413,0.034432,-0.010834
2022-02-10,0.004065,-0.055060,0.009091,0.016129,0.005963,0.032725,-0.004402,0.036534,0.008172,-0.002181
2022-02-11,0.000000,-0.027828,0.035559,-0.012073,-0.013166,0.047628,-0.017804,0.019979,0.024618,-0.004376
2022-02-14,-0.010706,-0.012423,0.006529,-0.031879,-0.015787,-0.064849,-0.004501,-0.051872,0.002478,-0.035718
2022-02-15,0.009691,0.096122,-0.008715,0.015552,-0.003679,-0.012485,0.000000,-0.006969,0.017178,0.002270
2022-02-16,0.005063,-0.008961,0.019502,0.010235,0.019465,0.002008,0.000752,0.032113,0.004854,0.065813
2022-02-17,0.002018,0.058794,-0.006459,0.042857,-0.003621,-0.002008,-0.013616,-0.013637,-0.019561,0.018928
2022-02-18,-0.006067,-0.035339,-0.002162,-0.030711,-0.024481,0.041827,0.004559,-0.009195,-0.002472,0.002081
2022-02-21,-0.008658,-0.001600,-0.006515,-0.005043,-0.002481,-0.004831,-0.007610,0.018307,-0.004963,-0.016772
2022-02-22,-0.021718,-0.053445,0.002176,-0.018368,-0.030267,0.000000,-0.010753,-0.013699,-0.022134,-0.025697
2022-02-23,-0.003666,0.047824,-0.006543,-0.009312,0.008923,-0.007290,0.003854,0.000000,0.027097,-0.008715
2022-02-24,-0.014267,-0.005652,0.047017,-0.031682,-0.052095,-0.048985,-0.018634,-0.037475,-0.025064,-0.063226
2022-02-25,-0.013934,0.038909,0.036889,0.068420,-0.014815,-0.039713,-0.004713,0.002384,0.005063,-0.009368

In [117]:
feb.sum()

0016.HK   -0.042784
2269.HK   -0.214383
1876.HK    0.140164
0268.HK    0.081380
1810.HK   -0.117632
2202.HK   -0.083808
0823.HK   -0.054399
0868.HK   -0.018868
0981.HK    0.044406
1928.HK   -0.050469
dtype: float64

In [142]:
#2月份回报
feb_return=np.dot(feb.sum(),get_best_weight(jan))+(-(market_log_price[0]))

In [172]:
feb_return

-0.007883074162140735

In [146]:
march=month_data('03','31')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [170]:
feb_std=np.sqrt(np.dot(feb.var(),get_best_weight(jan)))
feb_std

0.03567941485057133

In [171]:
feb_sharpe=(feb_return-0.00245)/feb_std
feb_sharpe

-0.2896088460367582

In [173]:
#二月份股票份额 9M future
get_best_weight(jan)*91

array([ 0.4107845 ,  5.33869029, 14.59195534, 10.95677801,  0.6464756 ,
        9.88551772, 17.85907533, 14.53079957, 12.67047826,  4.10944538])

In [147]:
#三月份回报
march_return=np.dot(march.sum(),get_best_weight(feb))+(-(market_log_price[1]))

In [148]:
apr=month_data('04','30')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [149]:
#四月份回报
april_return=np.dot(apr.sum(),get_best_weight(march))+(-(market_log_price[2]))

In [151]:
may=month_data('05','31')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [152]:
#5月份回报
may_return=np.dot(may.sum(),get_best_weight(apr))+(-(market_log_price[3]))

In [153]:
june=month_data('06','30')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [154]:
#6月份回报
june_return=np.dot(june.sum(),get_best_weight(may))+(-(market_log_price[4]))

In [155]:
july=month_data('07','31')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [156]:
#7月份回报
july_return=np.dot(july.sum(),get_best_weight(june))+(-(market_log_price[5]))

In [157]:
august=month_data('08','31')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [158]:
#8月份回报
august_return=np.dot(august.sum(),get_best_weight(july))+(-(market_log_price[6]))

In [159]:
sep=month_data('09','30')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [160]:
sep_return=np.dot(sep.sum(),get_best_weight(august))+(-(market_log_price[7]))

In [163]:
feb_return+march_return+april_return+may_return+june_return+july_return+august_return

-0.03919849081517174

In [167]:
market_log_ret[:9].sum()

-0.3235446904865952

In [ ]:
market_sharpe=(market_log_ret[:9].sum()-0.00245*8)/